baseURL = 'https://khushiramsingh680.github.io/containers/'
languageCode = 'en-us'
title = 'Learn containers'
theme = 'hugo-theme-relearn'
relativeURLs = true
canonifyURLs = true

[params]
  # Relearn theme-specific parameters
  colorTheme = "light"
  layout = "wide"

[[menu.main]]
  name = "Home"
  url = "/"
  weight = 1